---
contents:
  repositories:
    - '@local ./packages'
  keyring:
    - ./melange.rsa.pub
  packages:
    - xmrig-proxy@local

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
  run-as: 65532

entrypoint:
  command: /usr/bin/xmrig-proxy
...