---
name: build and push
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup qemu
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392  # v3.6.0
      - name: checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 0
      - name: build package
        uses: chainguard-dev/actions/melange-build@ce51233d303aed2394a9976e7f5642fd2158f693  # v1.1.1
        with:
          sign-with-temporary-key: true
      - name: build container
        uses: chainguard-images/actions/apko-publish@711a62d32118ee565db9c24249fc90011bdd7eb4  # v1.0.0
        with:
          tag: ${{ github.repository_owner }}/${{ github.repository }}:latest
...
